import { CourseSummary } from './models';

export const MOCK_COURSES: CourseSummary[] = [
  {
    id: 'course-db',
    name: 'قواعد البيانات',
    stage: 'الفرقة الثالثة',
    term: 'الفصل الأول 2026',
    description: 'مقدمة شاملة في تصميم قواعد البيانات العلائقية، التطبيع، ولغة SQL.',
    studentsCount: 18,
    lecturesCount: 4,
    avgScore: 78,
    status: 'active',
    updatedAt: '2026-09-10',
    color: '#4f5fd6',
    icon: '🗄️',
  },
  {
    id: 'course-ds',
    name: 'هياكل البيانات',
    stage: 'الفرقة الثانية',
    term: 'الفصل الأول 2026',
    description: 'الأشجار، القوائم المرتبطة، الأكوام، والخوارزميات الأساسية.',
    studentsCount: 22,
    lecturesCount: 3,
    avgScore: 71,
    status: 'active',
    updatedAt: '2026-09-08',
    color: '#10b981',
    icon: '🌳',
  },
  {
    id: 'course-science6',
    name: 'العلوم — الصف السادس الابتدائي',
    stage: 'ابتدائي',
    term: 'الترم الأول 2026',
    description: 'الكائنات الحية، دورة الحياة، والنظام البيئي المحيط بنا.',
    studentsCount: 26,
    lecturesCount: 2,
    avgScore: 84,
    status: 'active',
    updatedAt: '2026-09-12',
    color: '#f59e0b',
    icon: '🔬',
  },
];
